### ISSUE TITLE
[MNG-2727] Fix Logging in threadsafe components

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3965]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** opened **[MNG-2727](https://issues.apache.org/jira/browse/MNG-2727?redirect=false)** and commented

---

4 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

We have a general problem with plexus components that are singletons in that they use
he same logger for their lifespan. This is not good in that many requests may be fired
off and the singleton plexus component will continue to funnel their output to the same
logger. We need to be able to swap the logger.

**Comment by jira-importer** [comment]
**[Trygve Laugstøl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trygvis@inamo.no)** commented

Shouldn't the component use a monitor instead of logging in the cases where the output is useful on a per-build basis?

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

If it's relavent to the API of the application yes, if you want debug output or general tracing then this falls outside the monitor. Though this is a general problem that would be solved using a more direct use of log4j and it's NDC facilities.

**Comment by jira-importer** [comment]
**[Geoffrey De Smet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ge0ffrey.desmet)** commented

log4j has been unchanged (=dead?) for 4 years.
It's creator created slf4j with logback (AKA log4j 2), similar license, much better code, still maintained, but due to politics it never got the name "log4j 2".

**Comment by jira-importer** [comment]
**[jieryn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jieryn)** commented

Maven should use its own logging facade which then is backed by logback (which supports NDC). Then if Geki creates something even better down the road we can swap it under the covers without any issue.

See Spring Framework for the devastation depending on a specific logging mechanism can do.

**Comment by jira-importer** [comment]
**[Ceki Gülcü](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ceki@qos.ch)** commented

FYI, SLF4J supports MDC but not NDC. There are counter arguments for making SLF4J an optional dependency: see http://slf4j.org/faq.html#optional_dependency

However, whether you choose to depend on SLF4J or go through your own facade, I am fairly certain that neither approach will be future proof.

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

I am a bit unsure of exactly which application use-case is being addressed in this issue;

For the current concurrency effort (MNG-3004) my current favourite strategy is replacing the LoggerManager with a ConcurrentLoggerManager that
provides a MavenProject-aware proxy for the existing logger subsystem. Such a proxy would typically be able to collect all logger output for
the project to a single outputstream, no matter how this intertwines with other builds.

A rough draft of this logic can be seen in LifecycleThreadedBuilder line 164 & 167, where the MavenProject is associated with the current thread (Code is commented out because the current implementation is not good enough). This association changes logger output, and the setThisModuleComplete releases the output.

I fully sense that there may be some other use cases, possibly related to embedding. But it seems like a solution that captures the "logical stream" that constitutes the output from a single build should be expandable to these different cases.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Stuart is taking care of this as part of moving over to Guice. We just need to inject a threadsafe logger. There's no point in doing this in Plexus and in Guice.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

since the switch to Guice happened, is there anything still left to do here, or was it taken care of as suggested in the last comment?

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

I'm not really sure we need to do anything more about this issue, the 3.x logging seems to work fairly well in parallel.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.

Assignee, if you think you can fix this bug anytime soon, please reopen and proceed appropriately.

**Comment by rdiez** [comment]
For the record, the reason this bug report exists is that the intermixed build output is unreadable. GNU Make recognised this problem long ago, and now everybody is using its `--output-sync=recurse` option.
