### ISSUE TITLE
[MNG-6794] Add mvn add groupId/artifactId feature like NPM to maven

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#8487]
**[gaurav](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gaurav9822)** opened **[MNG-6794](https://issues.apache.org/jira/browse/MNG-6794?redirect=false)** and commented

The article 10 myths about java in 2019(https://developer.okta.com/blog/2019/07/15/java-myths-2019) list a nice feature which maven could add to it.

 

For NPM, Want to add a new dependency? Just run `npm i groupId/artifactId`.

 

do think it would be cool if Maven had something like `mvn add groupId/artifactId`

---
No further details from [MNG-6794](https://issues.apache.org/jira/browse/MNG-6794?redirect=false)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

You did not understand how Maven works. It operates on projects, not on a local dependency cache. Moreover, we require versions too.

**Comment by jira-importer** [comment]
**[Martin Kanters](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=martinkanters)** commented

[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o), I just want to verify we understood [gaurav](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gaurav9822) and the author of the article correctly (and that I understood your comment correctly). 

I interpreted the suggestion of [gaurav](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gaurav9822) as that you would be able to add the dependency to the pom.xml file by a mvn cmd (similarly like `npm i <package> --save` does). In this case it would operate on the project and not on the local dependency cache. In this case https://issues.apache.org/jira/browse/MDEP-699 is a duplicate.

If one wants to just download the dependency instead of adding it to the project's pom.xml, he could use [mvn dependency:get](https://maven.apache.org/plugins/maven-dependency-plugin/get-mojo.html).

[gaurav](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gaurav9822), can you give some clarity?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Martin Kanters](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=martinkanters), this could be at most a Dependency Plugin goal.

**Comment by jira-importer** [comment]
**[Martin Kanters](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=martinkanters)** commented

Agreed. mvn dependency:add with the same arguments as dependency:get seems fitting to me, but then again this would be a duplicate of MDEP-699.

**Comment by brunoborges** [comment]
This was implemented in Maven Dependency Plugin: https://github.com/apache/maven-dependency-plugin/pull/1599
